name: Deploy Package to Pypi

on:
  push: 
    branches: [main]
  workflow_dispatch: 

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build release distributions
        run: |
          pip install -r requirements.txt
          python3 ./project_updater.py "file=./pyproject.toml" "set-version-patch=${{ github.run_number }}"
          python3 -m build

      - name: Install and test distribution
        run: |
          pip install $(ls ./dist/*.whl | head -n 1)
          python3 -m pytest

      - name: Deploy distribution
        run: |
          python3 -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_GLOBAL_TOKEN }}
